### ISSUE TITLE
Error when try to upload the avatar

### ISSUE THREAD

**Issue by Ryozei** [suzuryg/face-emo#21]
Hi,
First of all, thanks for your work with face emo, I tested it in unity a bit and it's very easy and comfortable to use!. But... when I try to upload the avatar with VRChat SDK it gives me an error that prevents the upload, I attach the screenshot and message error from console. This only happens when I trying to upload it, when I test it in play mode with GestureManager it works normally.
I already tried to do it in a new project and the same problem occurs.

I really like Face Emo and want to use it, so I want to find a solution to the problem. Thank you for your attention in advance.

![Error message](https://github.com/suzuryg/face-emo/assets/84828626/6a097069-4826-4785-9295-a08cdde8ad12)
![Console error](https://github.com/suzuryg/face-emo/assets/84828626/8a80275e-3a87-44b0-9ece-ed0719bdd27d)
[Full message error.txt](https://github.com/suzuryg/face-emo/files/12327903/Full.message.error.txt)

**Comment by suzuryg** [comment]
Thank you for taking a liking to FaceEmo!

Upon checking the error message, it appears that there's a failure in disabling TrackingControl. Having an upload fail due to this is not desirable, so I plan to modify it so that even if an error occurs, the build doesn't fail.

If you'd like to use FaceEmo immediately, please remove the "Tracking Control Disabler" attached to the "FaceEmoPrefab". This will likely prevent the build error from occurring. However, be aware that due to the effects of the original TrackingControl integrated into the avatar, facial expressions might not function correctly. (If you'd like the expressions to work correctly, please manually disable all the TrackingControls for eyes and mouth located in the FX layer.)

Furthermore, I am still uncertain why the reported error occurs. It would be very helpful for my future enhancements if you could inform me under which circumstances the disabling of TrackingControl fails. Thank you!

**Comment by suzuryg** [comment]
If facial expressions are not working properly, instead of disabling the Tracking Control for eyes and mouth, another effective solution is to delete the layer controlling the facial expressions. Regardless of which method you choose, please remember to create a backup of the AnimatorController.
