### ISSUE TITLE
Deleting the linked avatar will cause the FaceEmo object to become unusable

### ISSUE THREAD

**Issue by lunetoiles** [suzuryg/face-emo#32]
If the linked avatar used to generate the initial FaceEmo object is deleted, it is not able to replace the avatar descriptor field with a reference to a different avatar. It will refuse all attempts to change this field.

This can cause problems for example if you wish to delete the original avatar, and have FaceEmo then instead change a different Avatar with the same face mesh and objects, or if the avatar is accidentally deleted for any other reason.

**Comment by suzuryg** [comment]
I was not able to reproduce the defect you mentioned in my environment. Even after deleting the linked avatar, another avatar can be attached to the TargetAvatar field of the FaceEmoLauncherComponent.

I would be grateful if you could provide me with more details about the conditions under which you reproduce the defect so that I can fix it.

**Comment by lunetoiles** [comment]
すみません、再現条件はアバターを消すだと思ってましたけどそれでけではなさそうです。あとでバックアップを解凍して詳細を集めます
