### ISSUE TITLE
[light request] I want to manipulate Eyebone for facial expressions.

### ISSUE THREAD

**Issue by tarsan-vr** [suzuryg/face-emo#47]
I first tried to use this tool to do a cross-eyed(Japanese: 寄り目), but found that Eyebone cannot be manipulated.
I will solve this in other ways, but if there are requests from others, I think it would be useful to be able to use the tool to manipulate Eyebone as well.

Cross-eyed may not be many requested,
but a sideways glance, avert one's eyes, etc. would look beautiful in a photo.

**Comment by suzuryg** [comment]
Eye bone control has the following issues and requires consideration of specifications
- Avatar mask setting required to move eye bones in FX layer
- When eye bones are controlled simultaneously with facial expressions, pseudo-eye tracking is disabled by the expression reset animation.

Also, I think the mainstream method is to control eye gaze independently, rather than synchronizing it with facial expressions.
https://booth.pm/ja/items/4742883
https://booth.pm/ja/items/3565283
Therefore, eye bone control may be outside the scope of FaceEmo.

**Comment by tarsan-vr** [comment]
Thanks for reply, I close this issues.
(sorry for mistake to reopen notification)
